

set nocompatible	" required
filetype off		" required

" set the runtime path to include Vundle and initilize
set rtp+=~/newbox/.vim/bundle/Vundle.vim
call vundle#begin()

" alternatively pass a paht wher Vundle should install plugins
" call vunle#begin('~/some/path/here')

" let vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'
Plugin 'tmhedberg/SimpylFold'
Plugin 'mattn/emmet-vim'
Plugin 'dracula/vim'
Plugin 'elixir-editors/vim-elixir'
Plugin 'jistr/vim-nerdtree-tabs'
" add all your plugins here (node older versions of Vundle
" user Bundle instead of Plugin

" ...

" All of your plugins must be added before the following line
call vundle#end()	" required
filetype plugin indent on "required

set splitbelow
set splitright

"split navigations
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" Enable folding
set foldmethod=indent
set foldlevel=99
" Enable folding with the spacebar
nnoremap <space> za

"let g:SimpylFold_docstring_preview=1

au BufNewFile, BufRead *.py
    \ set tabstop=4
    \ set softtabstop=4
    \ set shiftwidth=4
    \ set textwidth=79
    \ set expandtab
    \ set autoindent
    \ set fileformat=unix

au BufNewFile,BufRead *.js, *.html, *.css
    \ set tabstop=2
    \ set softtabstop=2
    \ set shiftwidth=2

set encoding=utf-8

" Nerdtree conf
let NERDTreeIgnore=['\.pyc$', '\~$'] "ignore files in NERDTree
" ******************************************************************************************
set nu

set listchars=eol:⏎,tab:␉·,trail:␠,nbsp:⎵
set list

" monokai sublime like
syntax enable
colorscheme northpole

" 
set incsearch "Show matches while searching
set hlsearch "Search highlighting

" Powerlin setup
python3 from powerline.vim import setup as powerline_setup
python3 powerline_setup()
python3 del powerline_setup

set laststatus=2

" https://github.com/jbgutierrez/vim-better-comments
" ErrorBetterComments
"HighlightBetterComments
"QuestionBetterComments
"StrikeoutBetterComments
"
"
"TodoBetterComments
